name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag your-dockerhub-username/your-app:$(date +%s)

    - name: Push the Docker image to DockerHub
      run: docker push your-dockerhub-username/your-app:$(date +%s)

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Server via SSH (Username and Password)
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker pull your-dockerhub-username/your-app:$(date +%s)
          docker stop your-app-container || true
          docker rm your-app-container || true
          docker run -d -p 3000:3000 --name your-app-container your-dockerhub-username/your-app:$(date +%s)
